### ISSUE TITLE
React-Redux group project Kanban board setup

### ISSUE THREAD

**Issue by for-ashraf** [for-ashraf/react-redux-group-project#21]
In this project, we are going to develop the React-redux group project. We are two team members, [Muhammad Ashraf](https://github.com/for-ashraf) and [Diego Yon](https://github.com/diegoyon) .
[Project Link](https://github.com/for-ashraf/react-redux-group-project) .

**Comment by BertrandConxy** [comment]
Hi team ✋ , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💪 
- Kanban is set up well
- equal distribution of tasks
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
